"""
URL configuration for server project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/register/', views.register, name='register'),
    path('api/verify-email/', views.verify_email, name='verify_email'),
    path('api/resend-verification/', views.resend_verification_email, name='resend_verification_email'),
    path('api/login/', views.LoginView.as_view(), name='login'),
    path('api/logout/', views.LogoutView.as_view(), name='logout'),
    path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('api/stats/summary/', views.stats_summary, name='stats_summary'),
    path('api/groups/', views.GroupListCreateView.as_view(), name='group_list'),
    path('api/groups/<int:group_id>/', views.group_detail, name='group_detail'),
    path('api/groups/<int:group_id>/messages/', views.message_list, name='message_list'),
    path('api/groups/<int:group_id>/sessions/', views.session_list, name='session_list'),
    path('api/groups/<int:group_id>/files/', views.file_list, name='file_list'),
    path('api/groups/<int:group_id>/notifications/', views.notification_list, name='notification_list'),
    path('api/groups/<int:group_id>/ratings/', views.rating_list, name='rating_list'),
    path('api/groups/<int:group_id>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('api/groups/<int:group_id>/rating/', views.GroupRatingView.as_view(), name='group_rating'),
    path('api/groups/<int:group_id>/join/', views.JoinGroupView.as_view(), name='group_join'),
    path('api/similar-groups/<int:group_id>/', views.similar_groups, name='similar_groups'),
    path('api/recommendations/', views.group_recommendations, name='group_recommendations'),
    path('api/forgot-password/', views.forgot_password, name='forgot_password'),
    path('api/reset-password/', views.reset_password, name='reset_password'),
]
