"""
URL configuration for server project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/register/', views.register, name='register'),
    path('api/verify-email/', views.verify_email, name='verify_email'),
    path('api/resend-verification/', views.resend_verification_email, name='resend_verification_email'),
    path('api/login/', views.LoginView.as_view(), name='login'),
    path('api/logout/', views.LogoutView.as_view(), name='logout'),
    path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('api/stats/summary/', views.stats_summary, name='stats_summary'),
    path('api/groups/', views.GroupListCreateView.as_view(), name='group_list'),
    path('api/groups/<int:group_id>/', views.group_detail, name='group_detail'),
    path('api/groups/<int:group_id>/update/', views.UpdateGroupView.as_view(), name='group_update'),
    path('api/groups/<int:group_id>/messages/', views.message_list, name='message_list'),
    path('api/groups/<int:group_id>/sessions/', views.session_list, name='session_list'),
    path('api/groups/<int:group_id>/files/', views.file_list, name='file_list'),
    path('api/groups/<int:group_id>/notifications/', views.notification_list, name='notification_list'),
    path('api/groups/<int:group_id>/ratings/', views.rating_list, name='rating_list'),
    path('api/groups/<int:group_id>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('api/groups/<int:group_id>/rating/', views.GroupRatingView.as_view(), name='group_rating'),
    path('api/groups/<int:group_id>/join/', views.JoinGroupView.as_view(), name='group_join'),
    path('api/groups/<int:group_id>/leave/', views.LeaveGroupView.as_view(), name='group_leave'),
    path('api/groups/<int:group_id>/delete/', views.DeleteGroupView.as_view(), name='group_delete'),
    path('api/similar-groups/<int:group_id>/', views.similar_groups, name='similar_groups'),
    path('api/recommendations/', views.group_recommendations, name='group_recommendations'),
    path('api/flashcards/folders/', views.FlashcardFolderView.as_view(), name='flashcard_folders'),
    path('api/flashcards/folders/<int:folder_id>/', views.FlashcardFolderDetailView.as_view(), name='flashcard_folder_detail'),
    path('api/flashcards/', views.FlashcardView.as_view(), name='flashcards'),
    path('api/flashcards/<int:flashcard_id>/', views.FlashcardDetailView.as_view(), name='flashcard_detail'),
    path('api/flashcards/<int:flashcard_id>/image/<str:image_type>/', views.FlashcardImageView.as_view(), name='flashcard_image'),
    path('api/user-growth/', views.user_growth, name='user_growth'),
    path('api/reports/', views.reports, name='reports'),
    path('api/popular-subjects/', views.popular_subjects, name='popular_subjects'),
    path('api/groups/<int:group_id>/notifications/clear/', views.clear_group_notifications, name='clear_group_notifications'),
    path('api/sessions/<int:session_id>/', views.GroupSessionRetrieveUpdateDeleteView.as_view(), name='session_detail'),
    path('api/sessions/<int:session_id>/join/', views.join_session, name='join_session'),
    path('api/groups/messages/<int:message_id>/', views.message_detail, name='message_detail'),
    path('api/files/<int:file_id>/delete/', views.GroupFileDeleteView.as_view(), name='file_delete'),
    path('api/files/<int:file_id>/download/', views.GroupFileDownloadView.as_view(), name='file_download'),
    path('api/auth/request-password-reset/', views.request_password_reset, name='request_password_reset'),
    path('api/auth/reset-password/', views.reset_password, name='reset_password'),

    path('api/auth/request-password-reset/', views.request_password_reset, name='request_password_reset'),
    path('api/auth/reset-password/', views.reset_password, name='reset_password'),
]

