# Generated by Django 5.1.5 on 2025-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_group_creator_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
