# Generated by Django 5.1.5 on 2025-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_groupsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_personality',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
