# Generated by Django 4.2.23 on 2025-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_flashcardfolder_flashcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard", name="answer", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="flashcard", name="question", field=models.TextField(blank=True),
        ),
    ]
