# Generated by Django 5.1.5 on 2025-07-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('year_level', models.CharField(max_length=50)),
                ('preferred_study_format', models.CharField(max_length=100)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
