# Generated by Django 4.2.23 on 2025-07-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_alter_flashcard_answer_alter_flashcard_question"),
        ("server", "0012_pendingregistration"),
    ]

    operations = []
