# Generated by Django 5.1.5 on 2025-07-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_flashcard_answer_alter_flashcard_question'),
        ('server', '0012_pendingregistration'),
    ]

    operations = [
    ]
