# Generated by Django 5.1.5 on 2025-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='target_hours',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='end_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupsession',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
