# Generated by Django 5.1.5 on 2025-07-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
