# Generated by Django 5.1.5 on 2025-07-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_groupsession_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsession',
            name='time',
        ),
    ]
