# Generated by Django 5.1.5 on 2025-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_report'),
        ('server', '0018_remove_groupsession_time'),
    ]

    operations = [
    ]
