# Generated by Django 5.1.5 on 2025-07-17 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_merge_0014_report_0018_remove_groupsession_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
