# Generated by Django 5.1.5 on 2025-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_groupsession_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='extra_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
