# Generated by Django 5.1.5 on 2025-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_groupsession_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='meeting_format',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
