# Generated by Django 5.1.5 on 2025-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_groupsession_meeting_format_groupsession_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_study_hours',
            field=models.FloatField(default=0),
        ),
    ]
