# Generated by Django 4.2.23 on 2025-08-31 16:54

from django.db import migrations, models
import server.storage


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0023_group_total_study_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests_hobbies",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of interests and hobbies"
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="answer_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=server.storage.CustomS3Storage(),
                upload_to="flashcard_images/",
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="question_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=server.storage.CustomS3Storage(),
                upload_to="flashcard_images/",
            ),
        ),
    ]
